class FacilityLaboratoryInvestigationsWorker
  include Sidekiq::Worker

  def initialize(facility_id, organisation_id)
    @facility_id = facility_id
    @organisation_id = organisation_id
    @old_facility_id = Organisation.find_by(id: organisation_id).facilities.order(:created_at => :asc)[0].id
    @all_investigations = LaboratoryInvestigationData.where(facility_id: @old_facility_id)
    if @all_investigations.count > 0
      @standard_investigations = @all_investigations.where(is_custom: false)
      @custom_investigations = @all_investigations.where(is_custom: true)
    end
  end

  def call
    if @all_investigations.count > 0
      create_standard_laboratory_investigations(@facility_id, @organisation_id)
      create_custom_laboratory_investigations(@facility_id, @organisation_id)
    else
      @new_investigations = new_standard_laboratory_investigations(@facility_id, @organisation_id)
      LaboratoryInvestigationData.create!(@new_investigations)
    end
  end

  def create_standard_laboratory_investigations(facility_id, organisation_id)
    @standard_investigations.each_with_index do |standard_inv|
      LaboratoryInvestigationData.create(srno: standard_inv.srno, investigation_name: standard_inv.investigation_name, short_name: standard_inv.short_name, loinc_class: standard_inv.loinc_class, test_type: standard_inv.test_type, specialty_id: standard_inv.specialty_id, facility_id: facility_id, organisation_id: organisation_id, has_sub_tests: standard_inv.has_sub_tests, investigation_id: standard_inv.investigation_id, is_custom: false, is_deleted: standard_inv.is_deleted, loinc_code: standard_inv.loinc_code, normal_range: standard_inv.normal_range, only_sub_test: standard_inv.only_sub_test, panel_ids: standard_inv.panel_ids)
    end
  end

  def create_custom_laboratory_investigations(facility_id, organisation_id)
    @custom_investigations.each_with_index do |custom_invest|
      LaboratoryInvestigationData.create(investigation_name: custom_invest.investigation_name, facility_id: facility_id, organisation_id: organisation_id, has_sub_tests: custom_invest.has_sub_tests, investigation_id: custom_invest.investigation_id, is_custom: true, is_deleted: custom_invest.is_deleted, loinc_code: custom_invest.loinc_code, normal_range: custom_invest.normal_range, only_sub_test: custom_invest.only_sub_test, panel_ids: custom_invest.panel_ids)
    end
  end

  def new_standard_laboratory_investigations(facility_id, organisation_id)
    ([
      { srno: 1, investigation_id: 130000001, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '17861-6', investigation_name: 'S. Calcium', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 2, investigation_id: 130000002, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '2777-1', investigation_name: 'S. Phosphates', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 3, investigation_id: 130000003, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '6768-6', investigation_name: 'Alk. Phosphatase', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 4, investigation_id: 130000004, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1989-3', investigation_name: '25(OH)D3 ', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 5, investigation_id: 130000005, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '2731-8', investigation_name: 'S. Parathyrin (PTH)', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 6, investigation_id: 130000006, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '2132-9', investigation_name: 'Vit B12', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 7, investigation_id: 130000007, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '3084-1', investigation_name: 'S. Uric acid', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 8, investigation_id: 130000008, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '718-7', investigation_name: 'Hgb', loinc_class: 'HEM/BC', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 9, investigation_id: 130000009, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '58410-2', investigation_name: 'CBC', loinc_class: 'PANEL.HEM/BC', test_type: 'P', normal_range: '', panel_ids: ['787-2', '4544-3', '6690-2', '777-3', '11067-6', '81638-9'], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: true },
      { srno: 10, investigation_id: 130000053, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '882-1', investigation_name: 'Blood Grouping', loinc_class: 'BLDBK', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 11, investigation_id: 130000054, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1250-0', investigation_name: 'Blood group cross matching', loinc_class: 'BLDBK', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 12, investigation_id: 130000010, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '30341-2', investigation_name: 'ESR', loinc_class: 'HEM/BC', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 13, investigation_id: 130000011, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1988-5', investigation_name: 'CRP', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 14, investigation_id: 130000012, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '74447-4', investigation_name: 'Urine Sugar', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 15, investigation_id: 130000040, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '2339-0', investigation_name: 'RBS', loinc_class: 'CHEM', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 16, investigation_id: 130000041, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1558-6', investigation_name: 'Fasting Sugar', loinc_class: 'CHAL', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 17, investigation_id: 130000042, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1504-0', investigation_name: 'PP Sugar', loinc_class: 'CHAL', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 18, investigation_id: 130000013, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '4548-4', investigation_name: 'Hgb A1c', loinc_class: 'HEM/BC', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      # Added Jan
      { srno: 19, investigation_id: 130000014, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '24325-3', investigation_name: 'LFT', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 20, investigation_id: 130000055, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-1', investigation_name: 'SGOT', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 21, investigation_id: 130000056, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-2', investigation_name: 'SGPT', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 22, investigation_id: 130000057, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-3', investigation_name: 'Bilirubin', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 23, investigation_id: 130000058, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-4', investigation_name: 'S. Proteins', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 24, investigation_id: 130000015, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '24362-6', investigation_name: 'RFT', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 25, investigation_id: 130000059, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-5', investigation_name: 'S. Creat', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 26, investigation_id: 130000060, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-6', investigation_name: 'BUN', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 27, investigation_id: 130000016, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '55231-5', investigation_name: 'Electrolytes', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 28, investigation_id: 130000061, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-7', investigation_name: 'S. Na', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 29, investigation_id: 130000062, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-8', investigation_name: 'S. K', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 30, investigation_id: 130000063, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '1238-9', investigation_name: 'S. Cl', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      # End Line
      { srno: 31, investigation_id: 130000017, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '48345-3', investigation_name: 'HIV', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 32, investigation_id: 130000018, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '5196-1', investigation_name: 'HBS Ag', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 33, investigation_id: 130000019, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '5198-7', investigation_name: 'HCV Ab', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 34, investigation_id: 130000043, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '5291-0', investigation_name: 'VDRL', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 35, investigation_id: 130000044, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '24314-7', investigation_name: 'TORCH', loinc_class: 'MICRO', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 36, investigation_id: 130000045, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '9422-7', investigation_name: 'HSV-IgG', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 37, investigation_id: 130000046, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '8040-8', investigation_name: 'Toxo-IgM', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 38, investigation_id: 130000047, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '8039-0  ', investigation_name: 'Toxo-IgG', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 39, investigation_id: 130000048, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '8015-0', investigation_name: 'Rubella-IgM', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 40, investigation_id: 130000049, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '8014-3', investigation_name: 'Rubella-IgG', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 41, investigation_id: 130000050, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '7853-5', investigation_name: 'CMV-IgM', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 42, investigation_id: 130000051, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '7852-7', investigation_name: 'CMV-IgG', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 43, investigation_id: 130000052, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '16944-1', investigation_name: 'HSV-IgM', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 44, investigation_id: 130000020, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '11572-5', investigation_name: 'RA Factor', loinc_class: 'SERO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 45, investigation_id: 130000021, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '33935-8', investigation_name: 'Anti-cCP Ab', loinc_class: 'SERO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 46, investigation_id: 130000022, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '8061-4', investigation_name: 'ANA', loinc_class: 'SERO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 47, investigation_id: 130000023, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '5130-0', investigation_name: 'dsDNA Ab', loinc_class: 'SERO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 48, investigation_id: 130000024, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '48073-1', investigation_name: 'Thyroid Profile', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 49, investigation_id: 130000025, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '53575-7', investigation_name: 'Lipid Profile', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 50, investigation_id: 130000026, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '34528-0', investigation_name: 'Coagulation Profile', loinc_class: 'PANEL.COAG', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 51, investigation_id: 130000027, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '50190-8', investigation_name: 'Iron Studies', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 52, investigation_id: 130000028, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '24351-9', investigation_name: 'Electrophoresis', loinc_class: 'PANEL.CHEM', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 53, investigation_id: 130000029, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '24357-6', investigation_name: 'Urine Analysis', loinc_class: 'PANEL.UA', test_type: 'P', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 54, investigation_id: 130000030, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '12235-8', investigation_name: 'Urine Microsocpy', loinc_class: 'UA', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 55, investigation_id: 130000031, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '630-4', investigation_name: 'Bacteria Urine Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 56, investigation_id: 130000032, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '600-7', investigation_name: 'Bacteria Blood Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 57, investigation_id: 130000033, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '6462-6', investigation_name: 'Bacteria Wound Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 58, investigation_id: 130000034, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '580-1', investigation_name: 'Fungus Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 59, investigation_id: 130000035, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '543-9', investigation_name: 'Mycobacterium Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 60, investigation_id: 130000036, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '635-3', investigation_name: 'Bacteria Anaerobe Culture', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 61, investigation_id: 130000037, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '23658-8', investigation_name: 'Bacteria Antibiotic Susceptibility', loinc_class: 'ABXBACT', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 62, investigation_id: 130000038, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '664-3', investigation_name: 'Gram Stn ', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 63, investigation_id: 130000039, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '655-1', investigation_name: 'Acid fast Stn', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 64, investigation_id: 130000064, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '#', investigation_name: 'Bio Chemistry', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: ['1558-6', '74447-4', '1504-0', '2345-7'], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: true },
      { srno: 65, investigation_id: 130000065, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '##', investigation_name: 'Haematology', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: ['11067-6', '81638-9', '718-7'], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: true },
      { srno: 66, investigation_id: 130000066, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '###', investigation_name: 'SEROLOGY', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: ['48159-8', '5195-3', '69668-2', '34532-2', '34530-6'], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: true },
      { srno: 67, investigation_id: 130000067, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '71575-5', investigation_name: 'ECG', loinc_class: 'MICRO', test_type: 'I', normal_range: '', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },
      { srno: 68, investigation_id: 130000068, facility_id: facility_id, organisation_id: organisation_id, loinc_code: '18725-2', investigation_name: 'MicroBiology', loinc_class: 'ATTACH.LAB', test_type: 'P', normal_range: 'No Organism seen in both eyes.', panel_ids: [], specialty_id: 309988001, is_deleted: false, is_custom: false, only_sub_test: false, has_sub_tests: false },

      # laboratory panel investigations list

      { srno: 69, investigation_id: 130000069, loinc_code: '787-2', investigation_name: 'Erythrocyte mean corpuscular volume [Entitic volume] by Automated count', short_name: 'Red blood cell count', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "Male: 4.32-5.72 trillion cells/L*(4.32-5.72 million cells/mcL**)\nFemale: 3.90-5.03 trillion cells/L(3.90-5.03 million cells/mcL)", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 70, investigation_id: 130000070, loinc_code: '4544-3', investigation_name: 'Hematocrit [Volume Fraction] of Blood by Automated count', short_name: 'Hematocrit', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "Male: 38.8-50.0 percent\nFemale: 34.9-44.5 percent", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 71, investigation_id: 130000071, loinc_code: '6690-2', investigation_name: ' Leukocytes [#/​volume] in Blood by Automated count', short_name: 'White blood cell count', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "3.5-10.5 billion cells/L\n(3,500 to 10,500 cells/mcL)", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 72, investigation_id: 130000072, loinc_code: '777-3', investigation_name: 'Platelets [#/​volume] in Blood by Automated count', short_name: 'Platelet count', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "150-450 billion/L\n(150,000 to 450,000/mcL**)", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 73, investigation_id: 130000073, loinc_code: '11067-6', investigation_name: 'Bleeding Time', short_name: 'BT', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "2-5 minutes", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 74, investigation_id: 130000074, loinc_code: '81638-9', investigation_name: 'Clotting Time', short_name: 'CT', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "3-7 minutes", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 75, investigation_id: 13000006675, loinc_code: '718-7a', investigation_name: 'Heamoglobin%', short_name: 'CT', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "Males 13-18gm% Females 11-16gm%", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 76, investigation_id: 130000075, loinc_code: '57021-8', investigation_name: 'Hematocrit (PCV)', short_name: 'PCV', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "30 - 45%", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 77, investigation_id: 130000076, loinc_code: '26464-8', investigation_name: 'Leucocyte count (WBC)', short_name: 'WBC', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "4,000 - 11,000 cells/cu.mm.", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 78, investigation_id: 130000077, loinc_code: '57021-8a', investigation_name: 'Erythrocyte count (RBC)', short_name: 'RBC', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "3.5 - 5.5 million cells/cu.mm.", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 79, investigation_id: 130000078, loinc_code: '26515-7', investigation_name: 'Platelet count', short_name: 'PC', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "1.5 - 4.0 Lakh cells/cu.mm.", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 80, investigation_id: 130000079, loinc_code: '4537-7', investigation_name: 'ESR', short_name: 'ESR', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "1/2 Hour : 05 - 10 mm,  1 Hour 10 - 20 mm", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 81, investigation_id: 130000080, loinc_code: '4548-4a', investigation_name: 'Glycocylated hemoglobin (HbA1C)', short_name: 'HbA1C', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "Non Diabetic : 4 - 6.5 %, Good control : 6.5 - 8.5%, Poor control : 8.5 - 10.5%", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 82, investigation_id: 130000081, loinc_code: '48159-8', investigation_name: 'HCV', short_name: 'HCV', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "NON REACTIVE", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 83, investigation_id: 130000082, loinc_code: '5195-3', investigation_name: 'Hbs Ag', short_name: 'Hbs Ab', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "NEGATIVE", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 84, investigation_id: 130000083, loinc_code: '69668-2', investigation_name: 'HIV ANTI BODY', short_name: 'HIV', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "NON REACTIVE", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 85, investigation_id: 130000084, loinc_code: '34532-2', investigation_name: 'BLOOD GROUP', short_name: 'BG', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 86, investigation_id: 130000085, loinc_code: '34530-6', investigation_name: 'Rh Type', short_name: 'Rh Type', loinc_class: 'HEM/BC/Lab', test_type: 'BC/Lab', specialty_id: 309988001, normal_range: "", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 87, investigation_id: 13000006686, loinc_code: '1558-6a', investigation_name: 'Fasting Blood Sugar', short_name: 'Fasting Blood Sugar', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: "60-110 mg/dl", only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 88, investigation_id: 130000087, loinc_code: '74447-4a', investigation_name: 'Corresponding  Urine Sugar', short_name: 'Urine Sugar', loinc_class: 'PANEL.CHEM', test_type: 'P', specialty_id: 261904005, normal_range: 'NIL', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 89, investigation_id: 130000088, loinc_code: '1504-0a', short_name: 'PP Sugar', investigation_name: 'Post Prandial Blood Sugar', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Less Than 180 mg/dl', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 90, investigation_id: 130000089, loinc_code: '6299-2', short_name: 'BU', investigation_name: 'Blood Urea', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '20 - 45 mg/dl', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 91, investigation_id: 130000090, loinc_code: '2160-0', short_name: 'SC', investigation_name: 'Serum Creatine', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Male : 0.7 - 1.4 mg/dl,  Female : 0.6 - 1.2 mg/dl', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 92, investigation_id: 130000091, loinc_code: '2345-7', short_name: 'Random blood Sugar', investigation_name: 'Random blood Sugar', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '70-160 mg/dl', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 93, investigation_id: 130000092, loinc_code: '5778-6', short_name: 'Color', investigation_name: 'COLOR', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 94, investigation_id: 130000093, loinc_code: '###-1', short_name: 'REACTION', investigation_name: 'REACTION', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 95, investigation_id: 130000094, loinc_code: '53327-3', short_name: '  Bilirubin.total [Mass/​volume] in Urine by Automated test strip', investigation_name: 'ALBUMIN', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 96, investigation_id: 130000095, loinc_code: '5792-7', short_name: 'Glucose [Mass/​volume] in Urine by Test strip', investigation_name: 'SUGAR', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },
      { srno: 97, investigation_id: 130000096, loinc_code: '###-2', short_name: 'Pus cells', investigation_name: 'PUS CELLS', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 98, investigation_id: 130000097, loinc_code: '###-3', short_name: 'EPITHELIAL CELLS', investigation_name: 'EPITHELIAL CELLS', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 99, investigation_id: 130000098, loinc_code: '789-8', short_name: 'RBC', investigation_name: 'RBC', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 100, investigation_id: 130000099, loinc_code: '###-4', short_name: 'CAST', investigation_name: 'CAST', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 101, investigation_id: 130000100, loinc_code: '###-5', short_name: 'CRYSTALS', investigation_name: 'CRYSTALS', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 102, investigation_id: 130000101, loinc_code: '###-6', short_name: 'BACTERIA', investigation_name: 'BACTERIA', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 103, investigation_id: 130000102, loinc_code: '###-7', short_name: 'OTHERS', investigation_name: 'OTHERS', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 104, investigation_id: 130000103, loinc_code: '2093-3', short_name: 'Cholesterol-Total(Serum,CHOD-POD)', investigation_name: 'Cholesterol-Total(Serum,CHOD-POD)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Desirable: < 200 Borderline High: 200-239 High: >= 240  Unit: mg/dL', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 105, investigation_id: 130000104, loinc_code: '2571-8', short_name: 'Triglycerides(Serum,GPO-POD)', investigation_name: 'Triglycerides(Serum,GPO-POD)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Normal: < 150 Borderline High: 150-199 High: 200-499 Very High: >= 500  Unit: mg/dL', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 106, investigation_id: 130000105, loinc_code: '2085-9', short_name: 'HDL Cholesterol(Serum,Direct Homogenous)', investigation_name: 'HDL Cholesterol(Serum,Direct Homogenous)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Major risk factor for heart disease: < 40 Negative risk factor for heart disease: >= 60  Unit: mg/dL', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 107, investigation_id: 130000106, loinc_code: '43396-1', short_name: 'Non HDL Cholesterol(Serum,Calculated)', investigation_name: 'Non HDL Cholesterol(Serum,Calculated)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Optimal: < 130 Desirable: 130-159 Borderline high: 159-189 High: 189-220 Very High: >= 220  Unit: mg/dL', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 108, investigation_id: 130000107, loinc_code: '18262-6', short_name: 'LDL Cholesterol(Serum,Calculated)', investigation_name: 'LDL Cholesterol (Serum,Calculated)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: 'Optimal: < 100 Near Optimal: 100-129 Borderline high: 130-159 High: 160-189 Very High: >= 190', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 109, investigation_id: 130000108, loinc_code: '11054-4', short_name: 'LDL/HDL RATIO', investigation_name: 'LDL/HDL RATIO', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '2.5-3.5 ratio', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] },

      { srno: 110, investigation_id: 130000109, loinc_code: '9830-1', short_name: 'CHOL/HDL RATIO(Serum,Calculated)', investigation_name: 'CHOL/HDL RATIO(Serum,Calculated)', loinc_class: 'PANEL.CHEM', test_type: 'I', specialty_id: 261904005, normal_range: '3.5-5 ratio', only_sub_test: true, facility_id: facility_id, organisation_id: organisation_id, is_deleted: false, is_custom: false, has_sub_tests: false, panel_ids: [] }
    ])
  end
end
