json.procedure_type @procedure_type
json.doctors_array @doctors_array
json.source @source
json.procedure_comment @procedure_comment
json.users_comment @users_comment
json.common_procedure @common_procedure
json.admission_doctor @admission_doctor
json.performed_by_id @performed_by_id
json.performed_datetime @performed_datetime
