MedicationList.create!(
  [
    { name: "ALLERPAT", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "ANTICET", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "BLURHEX", med_type: "SOLN", manufacturer: "Senses Pharma" },
    { name: "CELLWET", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "COMPU-TG", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "DIFLUSENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "DORSENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "DORSENZ-T", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "DUOBRIM-T", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "FACO", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "FLI DROPS", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "HYPERSENZ", med_type: "EYE DROP/OINT", manufacturer: "Senses Pharma" },
    { name: "KETSENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "LEOS", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "LEOS-MX", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "MACUVIT", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "NAPHACE", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "OBRIN", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "OBRIN-F", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "PARASENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "RETISIL", med_type: "OIL", manufacturer: "Senses Pharma" },
    { name: "RETISIL 1300", med_type: "OIL", manufacturer: "Senses Pharma" },
    { name: "SENSICLO", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENSOFI", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENSONAC", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZCIPRO", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "SENZMOX", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZMOX-KT", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZMOX-DX", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZPRED", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZVISC-TG", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "SERASENZ", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "SUPERNAC", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "T-PLUS", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "TRACETOL", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "TRAVASENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "EYE PAD", med_type: "EYE PAD", manufacturer: "Senses Pharma" },
    { name: "SURGI DRAPE", med_type: "DRAPE", manufacturer: "Senses Pharma" },
    { name: "TABLE DRAPE", med_type: "DRAPE", manufacturer: "Senses Pharma" },
    { name: "HH KIT", med_type: "KIT", manufacturer: "Senses Pharma" },
    { name: "SURGEON KIT", med_type: "KIT", manufacturer: "Senses Pharma" },
    { name: "PATIENT KIT", med_type: "KIT", manufacturer: "Senses Pharma" },
    { name: "HYPERSENZ", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "OBRIN", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "SENZCLOR-H", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "SENZMOX", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "ATROZEN", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "COMPU 0.5%", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "COMPU 1%", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "FLUNAREST 10", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "FLUNAREST 5", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "HOMISENZ", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "LEVOSENZ", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "NATASOL", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "OMISEN", med_type: "CAP", manufacturer: "Senses Pharma" },
    { name: "OMISEN-D", med_type: "CAP", manufacturer: "Senses Pharma" },
    { name: "SENSOLOL", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZPRED", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZCLOR", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "SENZMOX-DX", med_type: "EYE DROPS", manufacturer: "Senses Pharma" },
    { name: "SENZOMIDE", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "SENZOVIR", med_type: "EYE OINT", manufacturer: "Senses Pharma" },
    { name: "SENZVISC", med_type: "SOLN", manufacturer: "Senses Pharma" },
    { name: "VOLVIT", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "ZYTAMIN", med_type: "TAB", manufacturer: "Senses Pharma" },
    { name: "ZYTAMIN", med_type: "SYP", manufacturer: "Senses Pharma" },
    { name: "ZYTAPRO", med_type: "POWDER", manufacturer: "Senses Pharma" },
    { name: "SENSOMIDE", med_type: "TAB", manufacturer: "Senses Pharma" },

  ]
)
