TopIcdDiagnosis.delete_all

TopIcdDiagnosis.create!(
  [
    { specialty_id: 309988001, 'name' => 'Eyelid', list: [{ 'code' => 'H0002', 'name' => 'Hordeolum internum,Stye' }, { 'code' => 'H001', 'name' => 'Chalazion' }, { 'code' => 'H0102', 'name' => 'Squamous blepharitis' }, { 'code' => 'H0203', 'name' => 'Senile entropion' }, { 'code' => 'H0205', 'name' => 'Trichiasis' }, { 'code' => 'H0213', 'name' => 'Senile ectropion' }, { 'code' => 'H0220', 'name' => 'Lagophthalmos' }, { 'code' => 'H0240', 'name' => 'Ptosis' }] },
    { specialty_id: 309988001, 'name' => 'Lacrimal Gland', list: [{ 'code' => 'H0420', 'name' => 'Epiphora, watering' }, { 'code' => 'H0432', 'name' => 'Acute dacryocystitis' }, { 'code' => 'H0441', 'name' => 'Chronic dacryocystitis' }, { 'code' => 'H0453', 'name' => 'Neonatal obstruction of nasolacrimal duct' }, { 'code' => 'H0454', 'name' => 'Stenosis of lacrimal canaliculi' }, { 'code' => 'H0455', 'name' => 'Acquired stenosis of nasolacrimal duct' }, { 'code' => 'H0412', 'name' => 'Dry eye syndrome' }, { 'code' => 'H0414', 'name' => 'Primary lacrimal gland atrophy' }, { 'code' => 'H0415', 'name' => 'Secondary lacrimal gland atrophy' }] },
    { specialty_id: 309988001, 'name' => 'Orbit', list: [{ 'code' => 'H0501', 'name' => 'Cellulitis of orbit' }, { 'code' => 'H0500', 'name' => 'Preseptal cellulitis' }, { 'code' => 'H0520', 'name' => 'Exophthalmos' }, { 'code' => 'H0521', 'name' => 'Dystopia' }, { 'code' => 'H0524', 'name' => 'Constant exophthalmos' }, { 'code' => 'H0525', 'name' => 'Intermittent exophthalmos' }, { 'code' => 'H0526', 'name' => 'Pulsating exophthalmos' }, { 'code' => 'H0535', 'name' => 'Exostosis of orbit' }, { 'code' => 'H0540', 'name' => 'Enophthalmos' }] },
    { specialty_id: 309988001, 'name' => 'Conjunctival / Scleral Disorders', list: [{ 'code' => 'H100', 'name' => 'Mucopurulent conjunctivitis' }, { 'code' => 'B30', 'name' => 'Viral conjunctivitis' }, { 'code' => 'H1001', 'name' => 'Acute follicular conjunctivitis' }, { 'code' => 'H1040', 'name' => 'Chronic conjunctivitis' }, { 'code' => 'H1041', 'name' => 'Chronic giant papillary conjunctivitis' }, { 'code' => 'H1043', 'name' => 'Chronic follicular conjunctivitis' }, { 'code' => 'H1044', 'name' => 'Vernal conjunctivitis' }, { 'code' => 'H1100', 'name' => 'Pterygium' }, { 'code' => 'H1123', 'name' => 'Symblepharon' }, { 'code' => 'H1500', 'name' => 'Scleritis' }, { 'code' => 'H1510', 'name' => 'Episcleritis' }, { 'code' => 'T151', 'name' => 'Foreign body in conjunctival sac' }] },
    { specialty_id: 309988001, 'name' => 'Cornea', list: [{ 'code' => 'H1600', 'name' => 'Corneal ulcer' }, { 'code' => 'H1610', 'name' => 'Superficial keratitis' }, { 'code' => 'H1614', 'name' => 'Punctate keratitis' }, { 'code' => 'H1620', 'name' => 'Keratoconjunctivitis' }, { 'code' => 'H1625', 'name' => 'Phlyctenular keratoconjunctivitis' }, { 'code' => 'H1626', 'name' => 'Vernal keratoconjunctivitis, VKC' }, { 'code' => 'H1631', 'name' => 'Corneal abscess' }, { 'code' => 'H170', 'name' => 'Adherent leukoma' }, { 'code' => 'H171', 'name' => 'Central corneal opacity , NMCO' }, { 'code' => 'H181', 'name' => 'Bullous keratopathy' }, { 'code' => 'H1832', 'name' => 'Folds in Descemet\'s membrane' }, { 'code' => 'H1840', 'name' => 'Corneal degeneration' }, { 'code' => 'H1842', 'name' => 'Band keratopathy' }, { 'code' => 'H1845', 'name' => 'Nodular corneal degeneration' }, { 'code' => 'H1850', 'name' => 'Hereditary corneal dystrophies' }, { 'code' => 'H1860', 'name' => 'Keratoconus' }, { 'code' => 'Q133', 'name' => 'Congenital corneal opacity' }, { 'code' => 'H181', 'name' => 'Pseudophakic Bullous keratopathy PBK' }, { 'code' => 'H5901', 'name' => 'Aphakic Bullous keratopathy ABK' }, { 'code' => 'T542', 'name' => 'Acid injury' }, { 'code' => 'T543', 'name' => 'Alkali Injury' }, { 'code' => 'T150', 'name' => 'Foreign body in cornea' }] },
    { specialty_id: 309988001, 'name' => 'Uvea', list: [{ 'code' => 'H2000', 'name' => 'Acute and subacute iridocyclitis' }, { 'code' => 'H2005', 'name' => 'Hypopyon' }, { 'code' => 'H201', 'name' => 'Chronic iridocyclitis' }, { 'code' => 'H2081', 'name' => 'Fuchs\' heterochromic iridocyclitis' }, { 'code' => 'H210', 'name' => 'Hyphema' }, { 'code' => 'H2151', 'name' => 'Anterior synechiae, PAS' }, { 'code' => 'H2153', 'name' => 'Iridodialysis' }, { 'code' => 'H2154', 'name' => 'Posterior synechiae, PS' }, { 'code' => 'H2155', 'name' => 'Recession of chamber angle' }, { 'code' => 'H2181', 'name' => 'Floppy iris syndrome' }, { 'code' => 'H2182', 'name' => 'Plateau iris syndrome' }] },
    { specialty_id: 309988001, 'name' => 'Cataract', list: [{ "code" => "Z961", "name" => "Pseudophakia" }, { 'code' => 'H2501', 'name' => 'Cortical age-related cataract' }, { 'code' => 'H2504', 'name' => 'Posterior subcapsular cataract' }, { 'code' => 'H251', 'name' => 'Age-related nuclear cataract' }, { 'code' => 'H2600', 'name' => 'Infantile and juvenile cataract' }, { 'code' => 'H2610', 'name' => 'Traumatic cataract' }, { 'code' => 'H2620', 'name' => 'Complicated cataract' }, { 'code' => 'H270', 'name' => 'Aphakia' }, { 'code' => 'H2711', 'name' => 'Subluxation of lens' }] },
    { specialty_id: 309988001, 'name' => 'Retina', list: [{ 'code' => 'H3100', 'name' => 'Chorioretinal scars' }, { 'code' => 'H3101', 'name' => 'Macula scars of posterior pole' }, { 'code' => 'H3140', 'name' => 'Choroidal detachment' }, { 'code' => 'H3300', 'name' => 'Retinal detachment with retinal break , RD, RRD' }, { 'code' => 'H3301', 'name' => 'Retinal detachment with single break' }, { 'code' => 'H3305', 'name' => 'Total retinal detachment, TRD' }, { 'code' => 'H332', 'name' => 'Serous retinal detachment , ERD' }, { 'code' => 'H334', 'name' => 'Traction detachment of retina , TRD' }, { 'code' => 'H3331', 'name' => 'Horseshoe tear of retina without detachment' }, { 'code' => 'H341', 'name' => 'Central retinal artery occlusion, CRAO' }, { 'code' => 'H3481', 'name' => 'Central retinal vein occlusion, CRVO' }, { 'code' => 'H3483', 'name' => 'Branch retinal vein occlusion, BRVO' }, { 'code' => 'E0831', 'name' => 'Diabetic retinopathy, DR' }, { 'code' => 'H3503', 'name' => 'Hypertensive retinopathy, HTR' }, { 'code' => 'H3510', 'name' => 'Retinopathy of prematurity, ROP' }, { 'code' => 'H3571', 'name' => 'Central serous chorioretinopathy, CSR, CSSR' }, { 'code' => 'H431', 'name' => 'Vitreous hemorrhage, VH' }, { 'code' => 'H3552', 'name' => 'Retinitis Pigmentosa, RP' }] },
    { specialty_id: 309988001, 'name' => 'Glaucoma', list: [{ 'code' => 'H4004', 'name' => 'Steroid responder' }, { 'code' => 'H4005', 'name' => 'Ocular hypertension, OHT' }, { 'code' => 'H4011', 'name' => 'Primary open-angle glaucoma, OAG' }, { 'code' => 'H4012', 'name' => 'Low-tension glaucoma' }, { 'code' => 'H4013', 'name' => 'Pigmentary glaucoma' }, { 'code' => 'H4014', 'name' => 'Capsular glaucoma with pseudoexfoliation of lens' }, { 'code' => 'H4020', 'name' => 'Unspecified primary angle-closure glaucoma, ACG' }, { 'code' => 'H4021', 'name' => 'Acute angle-closure glaucoma' }, { 'code' => 'H4022', 'name' => 'Chronic angle-closure glaucoma' }] },
    { specialty_id: 309988001, 'name' => 'Optic  Nerve', list: [{ 'code' => 'H460', 'name' => 'Optic papillitis' }, { 'code' => 'H461', 'name' => 'Retrobulbar neuritis' }, { 'code' => 'H462', 'name' => 'Nutritional optic neuropathy' }, { 'code' => 'H463', 'name' => 'Toxic optic neuropathy' }, { 'code' => 'H4701', 'name' => 'Ischemic optic neuropathy' }, { 'code' => 'H4710', 'name' => 'Papilledema' }, { 'code' => 'H4720', 'name' => 'Optic atrophy' }, { 'code' => 'H4721', 'name' => 'Primary optic atrophy' }, { 'code' => 'H4723', 'name' => 'Glaucomatous optic atrophy' }, { 'code' => 'H4761', 'name' => 'Cortical blindness' }] },
    { specialty_id: 309988001, 'name' => 'Squint', list: [{ 'code' => 'H490', 'name' => 'Third [oculomotor] nerve palsy' }, { 'code' => 'H491', 'name' => 'Fourth [trochlear] nerve palsy' }, { 'code' => 'H492', 'name' => 'Sixth [abducent] nerve palsy' }, { 'code' => 'H5000', 'name' => 'Esotropia, Convergent squint' }, { 'code' => 'H5010', 'name' => 'Exotropia, Divergent squint' }, { 'code' => 'H5015', 'name' => 'Alternating exotropia, alternating divergent squint, ADS' }, { 'code' => 'H502', 'name' => 'Vertical strabismus' }, { 'code' => 'H5041', 'name' => 'Cyclotropia' }, { 'code' => 'H5042', 'name' => 'Monofixation syndrome' }, { 'code' => 'H5051', 'name' => 'Esophoria' }, { 'code' => 'H5052', 'name' => 'Exophoria' }, { 'code' => 'H5081', 'name' => 'Duane\'s syndrome, DRS' }] },
    { specialty_id: 309988001, 'name' => 'Refraction', list: [{ 'code' => 'H520', 'name' => 'Hypermetropia' }, { 'code' => 'H521', 'name' => 'Myopia' }, { 'code' => 'H5222', 'name' => 'Regular astigmatism' }, { 'code' => 'H5231', 'name' => 'Anisometropia' }, { 'code' => 'H524', 'name' => 'Presbyopia' }, { 'code' => 'H5301', 'name' => 'Deprivation amblyopia' }, { 'code' => 'H5302', 'name' => 'Refractive amblyopia' }, { 'code' => 'H5303', 'name' => 'Strabismic amblyopia' }, { 'code' => 'H532', 'name' => 'Diplopia' }, { 'code' => 'H5331', 'name' => 'Abnormal retinal correspondence' }, { 'code' => 'H5310', 'name' => 'Computer vision syndrome' }, { 'code' => 'H5360', 'name' => 'Night blindness' }, { 'code' => 'H550', 'name' => 'Nystagmus' }] },
    { specialty_id: 309988001, 'name' => 'Disorders of globe', list: [{ 'code' => 'H4400', 'name' => 'Purulent endophthalmitis' }, { 'code' => 'H4401', 'name' => 'Panophthalmitis (acute)' }, { 'code' => 'H4411', 'name' => 'Panuveitis' }, { 'code' => 'H4444', 'name' => 'Primary hypotony of eye' }, { 'code' => 'H4451', 'name' => 'Absolute glaucoma' }, { 'code' => 'H4452', 'name' => 'Atrophy of globe' }, { 'code' => 'H4453', 'name' => 'Leucocoria' }, { 'code' => 'H5701', 'name' => 'Argyll Robertson pupil, atypical' }, { 'code' => 'H5702', 'name' => 'Anisocoria' }, { 'code' => 'H5703', 'name' => 'Miosis' }, { 'code' => 'H5704', 'name' => 'Mydriasis' }, { 'code' => 'H5705', 'name' => 'Tonic pupil' }, { 'code' => 'H571', 'name' => 'Ocular pain' }, { 'code' => 'Q111', 'name' => 'Anophthalmos' }, { 'code' => 'Q112', 'name' => 'Microphthalmos' }, { 'code' => 'Q113', 'name' => 'Macrophthalmos' }, { 'code' => 'S0110', 'name' => 'Open wound of eyelid & periocular area' }, { 'code' => 'S023', 'name' => 'Fracture of orbital floor' }] },
    { specialty_id: 309988001, 'name' => 'Normal/Miscellaneous/Others', list: [{ 'code' => 'Z0100', 'name' => 'Normal vision' }] }
  ]
)
